backend:
  name: git-gateway
  branch: cms # Branch to update (optional; defaults to main)
media_folder: 'public/images/uploads' # Media files will be stored in the repo under public/images/uploads
public_folder: 'images/uploads'
collections:
  - name: 'press-releases'
    label: 'Press Releases'
    folder: '_content/press-releases'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          time_format: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
